### ISSUE TITLE
Comments on paper

### ISSUE THREAD

**Issue by dpsanders** [joglekara/VlaPy#89]
- Why is the axis arbitrary in fig. 4 of the paper?

- It's not clear what you mean by a "fully integrated workflow".

**Comment by joglekara** [comment]
> Why is the axis arbitrary in fig. 4 of the paper?

It's because the field solver works over arbitrary axes. It's effectively just a Poisson solve in the spectral domain, so the physical dimension does not matter. This was also raised by @TomGoffrey , so I'm happy to change the label to be more specific to this application if that's better. I've just left it this way because it is still technically correct.

**Comment by dpsanders** [comment]
OK thanks. (Added another comment in the list)

**Comment by joglekara** [comment]
> * It's not clear what you mean by a "fully integrated workflow".

I meant
`the fully integrated workflow of running a simulation on a local machine and sending the results to the MLFlow-driven logging mechanism.`

Does that make sense? I've added that line to the paper as well.

**Comment by dpsanders** [comment]
Thanks, that makes more sense.
